`conda activate r_python`

In [ ]:
import warnings
warnings.filterwarnings('ignore')

import scanpy as sc
import numpy as np
import pandas as pd
import anndata as ad

import scib

In [ ]:
# multivi_modality_sampleid_cov = sc.read('mosaic_integration/multivi/trained_multivi_modality_sampleid_covariate/dmg_atlas_subset_multivi.h5ad')
multivi_sampleid = sc.read('mosaic_integration/multivi/trained_multivi_sampleID/dmg_atlas_subset_multivi.h5ad')
multivi_modality = sc.read('mosaic_integration/multivi/trained_multivi/dmg_atlas_subset_multivi.h5ad')

glue_modality = sc.read('mosaic_integration/scglue/modality/dmg_atlas_subset_scglue_modality.h5ad')
glue_modality_batch_cov = sc.read('mosaic_integration/scglue/modality_batch_covariate/dmg_atlas_subset_scglue_modality_batch_covariate.h5ad')


multigrate_modality = sc.read('mosaic_integration/multigrate/trained_multigrate_modality/dmg_atlas_subset_multigrate_modality.h5ad')
multigrate_modality_batch_cov = sc.read('mosaic_integration/multigrate/trained_multigrate_modality_batch/dmg_atlas_subset_multigrate_modality.h5ad')

/home/cruiz2/miniconda3/envs/r_python/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/cruiz2/miniconda3/envs/r_python/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

In [ ]:
# Assuming `multivi_sampleid.obs_names` is a pandas Index object
obs_names = multivi_sampleid.obs_names

new_obs_names = obs_names.str.replace('_paired', '').str.replace('_accessibility', '').str.replace('_expression', '')
new_obs_names

Index(['GNG_region_11_AAACATGCACGAACAG-1', 'GNG_region_11_AAACCAACACGTTACA-1',
       'GNG_region_11_AAACCAACATGATTGT-1', 'GNG_region_11_AAACGCGCATAAGGAC-1',
       'GNG_region_11_AAACGTACAATAACCT-1', 'GNG_region_11_AAACGTACAATCCTAG-1',
       'GNG_region_11_AAAGCACCACTTACAG-1', 'GNG_region_11_AAAGCGGGTTTCCGGC-1',
       'GNG_region_11_AAAGCTTGTACCTTAC-1', 'GNG_region_11_AAAGGACGTATTCGCT-1',
       ...
       'atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1',
       'atac_P-6255_S-8500_TTCAACTTCGATATGC-1',
       'atac_P-6255_S-8500_TTCATCATCAATCGTG-1',
       'atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1',
       'atac_P-6255_S-8500_TTGCACCGTATACGCT-1',
       'atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1',
       'atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1',
       'atac_P-6255_S-8500_TTGCTTATCCAACGCG-1',
       'atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1',
       'atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1'],
      dtype='object', length=70797)

In [ ]:
# Assign the updated values back to the original index
multivi_sampleid.obs_names = new_obs_names

# Print the updated obs_names
print(multivi_sampleid.obs_names)

Index(['GNG_region_11_AAACATGCACGAACAG-1', 'GNG_region_11_AAACCAACACGTTACA-1',
       'GNG_region_11_AAACCAACATGATTGT-1', 'GNG_region_11_AAACGCGCATAAGGAC-1',
       'GNG_region_11_AAACGTACAATAACCT-1', 'GNG_region_11_AAACGTACAATCCTAG-1',
       'GNG_region_11_AAAGCACCACTTACAG-1', 'GNG_region_11_AAAGCGGGTTTCCGGC-1',
       'GNG_region_11_AAAGCTTGTACCTTAC-1', 'GNG_region_11_AAAGGACGTATTCGCT-1',
       ...
       'atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1',
       'atac_P-6255_S-8500_TTCAACTTCGATATGC-1',
       'atac_P-6255_S-8500_TTCATCATCAATCGTG-1',
       'atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1',
       'atac_P-6255_S-8500_TTGCACCGTATACGCT-1',
       'atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1',
       'atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1',
       'atac_P-6255_S-8500_TTGCTTATCCAACGCG-1',
       'atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1',
       'atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1'],
      dtype='object', length=70797)

In [ ]:
# Assuming `multivi_modality.obs_names` is a pandas Index object
obs_names = multivi_modality.obs_names

new_obs_names = obs_names.str.replace('_paired', '').str.replace('_accessibility', '').str.replace('_expression', '')
new_obs_names

Index(['GNG_region_11_AAACATGCACGAACAG-1', 'GNG_region_11_AAACCAACACGTTACA-1',
       'GNG_region_11_AAACCAACATGATTGT-1', 'GNG_region_11_AAACGCGCATAAGGAC-1',
       'GNG_region_11_AAACGTACAATAACCT-1', 'GNG_region_11_AAACGTACAATCCTAG-1',
       'GNG_region_11_AAAGCACCACTTACAG-1', 'GNG_region_11_AAAGCGGGTTTCCGGC-1',
       'GNG_region_11_AAAGCTTGTACCTTAC-1', 'GNG_region_11_AAAGGACGTATTCGCT-1',
       ...
       'atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1',
       'atac_P-6255_S-8500_TTCAACTTCGATATGC-1',
       'atac_P-6255_S-8500_TTCATCATCAATCGTG-1',
       'atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1',
       'atac_P-6255_S-8500_TTGCACCGTATACGCT-1',
       'atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1',
       'atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1',
       'atac_P-6255_S-8500_TTGCTTATCCAACGCG-1',
       'atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1',
       'atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1'],
      dtype='object', length=70797)

In [ ]:
# Assign the updated values back to the original index
multivi_modality.obs_names = new_obs_names

# Print the updated obs_names
print(multivi_modality.obs_names)

Index(['GNG_region_11_AAACATGCACGAACAG-1', 'GNG_region_11_AAACCAACACGTTACA-1',
       'GNG_region_11_AAACCAACATGATTGT-1', 'GNG_region_11_AAACGCGCATAAGGAC-1',
       'GNG_region_11_AAACGTACAATAACCT-1', 'GNG_region_11_AAACGTACAATCCTAG-1',
       'GNG_region_11_AAAGCACCACTTACAG-1', 'GNG_region_11_AAAGCGGGTTTCCGGC-1',
       'GNG_region_11_AAAGCTTGTACCTTAC-1', 'GNG_region_11_AAAGGACGTATTCGCT-1',
       ...
       'atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1',
       'atac_P-6255_S-8500_TTCAACTTCGATATGC-1',
       'atac_P-6255_S-8500_TTCATCATCAATCGTG-1',
       'atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1',
       'atac_P-6255_S-8500_TTGCACCGTATACGCT-1',
       'atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1',
       'atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1',
       'atac_P-6255_S-8500_TTGCTTATCCAACGCG-1',
       'atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1',
       'atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1'],
      dtype='object', length=70797)

In [ ]:
multivi_sampleid

AnnData object with n_obs × n_vars = 70797 × 25000
    obs: 'nCount_RNA', 'nFeature_RNA', 'nCount_RAW', 'nFeature_RAW', 'DF.class', 'DF.score', 'scDblFinder.class', 'scDblFinder.score', 'ID', 'SampleID', 'Data', 'percent_mito', 'percent_ribo', 'percent_mito_ribo', 'log10GenesPerUMI', 'nFeature_Diff', 'nCount_Diff', 'Batch_for_correction', 'scDblFinder.clusters.class', 'scDblFinder.clusters.score', 'scDblFinder.class.clusters', 'doublet.combn.fisher', 'doublet.combn.mean', 'doublet.combn.fisher.class', 'doublet.combn.mean.class', 'Study', 'Original_annotation', 'Isolation_method_by_cell', 'Cell_type_granular_mouse_correlations', 'Cell_type_mouse_correlations', 'Cell_type_consensus_Jessa2022', 'Malignant_normal_consensus_Jessa2022', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'RNA_snn_res.0.8', 'seurat_clusters', 'predicted.annotation_level_1.score', 'predicted.annotation_level_1', 'predicted.annotation_level_2.score', 'predicted.annotation_level_2', 'predicted.annotation_level_3.score', 'predicted.annotation_level_3', 'predicted.annotation_level_4.score', 'predicted.annotation_level_4', 'iCNV', 'cell_id', 'predicted.id', 'Modality', 'gex_barcode', 'atac_barcode', 'is_cell', 'excluded_reason', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'passed_filters', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'nCount_ATAC', 'nFeature_ATAC', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'pct_reads_in_peaks', 'blacklist_ratio', 'high.tss', 'nucleosome_group', 'amulet_pvalue', 'amulet_qvalue', 'scDblFinder.p', 'dbl_combined_score', 'total', 'duplicate', 'chimeric', 'unmapped', 'lowmapq', 'mitochondrial', 'nonprimary', 'is__cell_barcode', 'TSS_fragments', 'DNase_sensitive_region_fragments', 'enhancer_region_fragments', 'promoter_region_fragments', 'on_target_fragments', 'blacklist_region_fragments', 'peak_region_fragments', 'peak_region_cutsites', 'modality', '_indices', '_scvi_batch', '_scvi_labels'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'chr', 'start', 'end', 'name', 'score', 'strand', 'thickStart', 'thickEnd', 'itemRgb', 'blockCount', 'blockSizes', 'blockStarts', 'gene_id', 'gene_version', 'gene_type', 'hgnc_id', 'tag', 'havana_gene', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'modality', 'count', 'percentile'
    uns: 'Study_colors', '_scvi_manager_uuid', '_scvi_uuid', 'cell_id_colors', 'modality_colors', 'neighbors', 'umap'
    obsm: 'MultiVI_latent', 'X_pca', 'X_ref.pca', 'X_ref.umap', 'X_umap'
    layers: 'counts', 'log-norm', 'tf-idf'
    obsp: 'connectivities', 'distances'

In [ ]:
multivi_modality

AnnData object with n_obs × n_vars = 70797 × 25000
    obs: 'nCount_RNA', 'nFeature_RNA', 'nCount_RAW', 'nFeature_RAW', 'DF.class', 'DF.score', 'scDblFinder.class', 'scDblFinder.score', 'ID', 'SampleID', 'Data', 'percent_mito', 'percent_ribo', 'percent_mito_ribo', 'log10GenesPerUMI', 'nFeature_Diff', 'nCount_Diff', 'Batch_for_correction', 'scDblFinder.clusters.class', 'scDblFinder.clusters.score', 'scDblFinder.class.clusters', 'doublet.combn.fisher', 'doublet.combn.mean', 'doublet.combn.fisher.class', 'doublet.combn.mean.class', 'Study', 'Original_annotation', 'Isolation_method_by_cell', 'Cell_type_granular_mouse_correlations', 'Cell_type_mouse_correlations', 'Cell_type_consensus_Jessa2022', 'Malignant_normal_consensus_Jessa2022', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'RNA_snn_res.0.8', 'seurat_clusters', 'predicted.annotation_level_1.score', 'predicted.annotation_level_1', 'predicted.annotation_level_2.score', 'predicted.annotation_level_2', 'predicted.annotation_level_3.score', 'predicted.annotation_level_3', 'predicted.annotation_level_4.score', 'predicted.annotation_level_4', 'iCNV', 'cell_id', 'predicted.id', 'Modality', 'gex_barcode', 'atac_barcode', 'is_cell', 'excluded_reason', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'passed_filters', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'nCount_ATAC', 'nFeature_ATAC', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'pct_reads_in_peaks', 'blacklist_ratio', 'high.tss', 'nucleosome_group', 'amulet_pvalue', 'amulet_qvalue', 'scDblFinder.p', 'dbl_combined_score', 'total', 'duplicate', 'chimeric', 'unmapped', 'lowmapq', 'mitochondrial', 'nonprimary', 'is__cell_barcode', 'TSS_fragments', 'DNase_sensitive_region_fragments', 'enhancer_region_fragments', 'promoter_region_fragments', 'on_target_fragments', 'blacklist_region_fragments', 'peak_region_fragments', 'peak_region_cutsites', 'modality', '_indices', '_scvi_batch', '_scvi_labels'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'chr', 'start', 'end', 'name', 'score', 'strand', 'thickStart', 'thickEnd', 'itemRgb', 'blockCount', 'blockSizes', 'blockStarts', 'gene_id', 'gene_version', 'gene_type', 'hgnc_id', 'tag', 'havana_gene', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'modality', 'count', 'percentile'
    uns: 'ID_colors', 'Study_colors', '_scvi_manager_uuid', '_scvi_uuid', 'cell_id_colors', 'modality_colors', 'neighbors', 'umap'
    obsm: 'MultiVI_latent', 'X_pca', 'X_ref.pca', 'X_ref.umap', 'X_umap'
    layers: 'counts', 'log-norm', 'tf-idf'
    obsp: 'connectivities', 'distances'

In [ ]:
glue_modality

AnnData object with n_obs × n_vars = 88672 × 0
    obs: 'scDblFinder.class', 'scDblFinder.score', 'ID', 'SampleID', 'Batch_for_correction', 'Study', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'cell_id', 'modality', 'domain', 'predicted.id', 'batch', 'balancing_weight'
    uns: 'cell_id_colors', 'domain_colors', 'modality_colors', 'neighbors', 'umap'
    obsm: 'X_glue', 'X_umap'
    layers: 'counts'
    obsp: 'connectivities', 'distances'

In [ ]:
glue_modality_batch_cov

AnnData object with n_obs × n_vars = 88672 × 0
    obs: 'scDblFinder.class', 'scDblFinder.score', 'ID', 'SampleID', 'Batch_for_correction', 'Study', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'cell_id', 'modality', 'domain', 'predicted.id', 'batch', 'balancing_weight'
    uns: 'cell_id_colors', 'domain_colors', 'modality_colors', 'neighbors', 'umap'
    obsm: 'X_glue', 'X_umap'
    layers: 'counts'
    obsp: 'connectivities', 'distances'

In [ ]:
multigrate_modality

AnnData object with n_obs × n_vars = 70797 × 25000
    obs: 'nCount_RNA', 'nFeature_RNA', 'nCount_RAW', 'nFeature_RAW', 'DF.class', 'DF.score', 'scDblFinder.class', 'scDblFinder.score', 'ID', 'SampleID', 'Data', 'percent_mito', 'percent_ribo', 'percent_mito_ribo', 'log10GenesPerUMI', 'nFeature_Diff', 'nCount_Diff', 'Batch_for_correction', 'scDblFinder.clusters.class', 'scDblFinder.clusters.score', 'scDblFinder.class.clusters', 'doublet.combn.fisher', 'doublet.combn.mean', 'doublet.combn.fisher.class', 'doublet.combn.mean.class', 'Study', 'Original_annotation', 'Isolation_method_by_cell', 'Cell_type_granular_mouse_correlations', 'Cell_type_mouse_correlations', 'Cell_type_consensus_Jessa2022', 'Malignant_normal_consensus_Jessa2022', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'RNA_snn_res.0.8', 'seurat_clusters', 'predicted.annotation_level_1.score', 'predicted.annotation_level_1', 'predicted.annotation_level_2.score', 'predicted.annotation_level_2', 'predicted.annotation_level_3.score', 'predicted.annotation_level_3', 'predicted.annotation_level_4.score', 'predicted.annotation_level_4', 'iCNV', 'cell_id', 'Modality', 'group', 'TSS.enrichment', 'TSS.percentile', 'amulet_pvalue', 'amulet_qvalue', 'blacklist_ratio', 'dbl_combined_score', 'excluded_reason', 'high.tss', 'nCount_ATAC', 'nFeature_ATAC', 'nucleosome_group', 'nucleosome_percentile', 'nucleosome_signal', 'passed_filters', 'pct_reads_in_peaks', 'predicted.id', 'scDblFinder.p', 'size_factors', '_scvi_batch'
    var: 'modality'
    obsm: 'X_umap', '_scvi_extra_categorical_covs', 'latent', 'latent_ref'
    layers: 'counts'
    obsp: 'connectivities', 'distances'

In [ ]:
multigrate_modality_batch_cov

AnnData object with n_obs × n_vars = 70797 × 25000
    obs: 'nCount_RNA', 'nFeature_RNA', 'nCount_RAW', 'nFeature_RAW', 'DF.class', 'DF.score', 'scDblFinder.class', 'scDblFinder.score', 'ID', 'SampleID', 'Data', 'percent_mito', 'percent_ribo', 'percent_mito_ribo', 'log10GenesPerUMI', 'nFeature_Diff', 'nCount_Diff', 'Batch_for_correction', 'scDblFinder.clusters.class', 'scDblFinder.clusters.score', 'scDblFinder.class.clusters', 'doublet.combn.fisher', 'doublet.combn.mean', 'doublet.combn.fisher.class', 'doublet.combn.mean.class', 'Study', 'Original_annotation', 'Isolation_method_by_cell', 'Cell_type_granular_mouse_correlations', 'Cell_type_mouse_correlations', 'Cell_type_consensus_Jessa2022', 'Malignant_normal_consensus_Jessa2022', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'RNA_snn_res.0.8', 'seurat_clusters', 'predicted.annotation_level_1.score', 'predicted.annotation_level_1', 'predicted.annotation_level_2.score', 'predicted.annotation_level_2', 'predicted.annotation_level_3.score', 'predicted.annotation_level_3', 'predicted.annotation_level_4.score', 'predicted.annotation_level_4', 'iCNV', 'cell_id', 'Modality', 'group', 'TSS.enrichment', 'TSS.percentile', 'amulet_pvalue', 'amulet_qvalue', 'blacklist_ratio', 'dbl_combined_score', 'excluded_reason', 'high.tss', 'nCount_ATAC', 'nFeature_ATAC', 'nucleosome_group', 'nucleosome_percentile', 'nucleosome_signal', 'passed_filters', 'pct_reads_in_peaks', 'predicted.id', 'scDblFinder.p', 'size_factors', '_scvi_batch'
    var: 'modality'
    obsm: 'X_umap', '_scvi_extra_categorical_covs', 'latent', 'latent_ref'
    layers: 'counts'
    obsp: 'connectivities', 'distances'

In [ ]:
unintegrated = sc.read('mosaic_integration/unintegrated/dmg_atlas_subset_rna_unintegrated.h5ad')

obs_names_to_keep = unintegrated.obs_names

unintegrated = unintegrated[unintegrated.obs_names.isin(obs_names_to_keep)].copy()

multivi_sampleid = multivi_sampleid[multivi_sampleid.obs_names.isin(obs_names_to_keep)].copy()

multivi_modality = multivi_modality[multivi_modality.obs_names.isin(obs_names_to_keep)].copy()

glue_modality = glue_modality[glue_modality.obs['domain'].isin(['scRNA-seq'])].copy()

glue_modality_batch_cov = glue_modality_batch_cov[glue_modality_batch_cov.obs['domain'].isin(['scRNA-seq'])].copy()

multigrate_modality = multigrate_modality[multigrate_modality.obs_names.isin(obs_names_to_keep)].copy()

multigrate_modality_batch_cov = multigrate_modality_batch_cov[multigrate_modality_batch_cov.obs_names.isin(obs_names_to_keep)].copy()

In [ ]:
unintegrated.shape[0], multivi_modality.shape[0], multivi_sampleid.shape[0], glue_modality.shape[0], glue_modality_batch_cov.shape[0], multigrate_modality.shape[0], multigrate_modality_batch_cov.shape[0]

(48993, 48993, 48993, 48993, 48993, 48993, 48993)

In [ ]:
dims = unintegrated.shape[0], multivi_modality.shape[0], multivi_sampleid.shape[0], glue_modality.shape[0], glue_modality_batch_cov.shape[0], multigrate_modality.shape[0], multigrate_modality_batch_cov.shape[0]

In [ ]:
# Assert that all dimensions are equal to the dimension of unintegrated.shape[0]
assert all(dim == unintegrated.shape[0] for dim in dims)

In [ ]:
# multigrate does not return pca embedding. 
# Assuiming MultiVAE latent representation can be used for metrics comparison

multigrate_modality.obsm['X_pca'] = multigrate_modality.obsm['latent_ref']
multigrate_modality_batch_cov.obsm['X_pca'] = multigrate_modality_batch_cov.obsm['latent_ref']

In [ ]:
# scGLUE does not return pca embedding. 
# Assuiming X_glue latent representation can be used for metrics comparison

glue_modality.obsm['X_pca'] = glue_modality.obsm['X_glue']
glue_modality_batch_cov.obsm['X_pca'] = glue_modality_batch_cov.obsm['X_glue']

In [ ]:
# multivi does return pca embedding. 
# Assuiming MultiVI_latent representation can be used for metrics comparison

multivi_modality.obsm['X_pca'] = multivi_modality.obsm['MultiVI_latent']
multivi_sampleid.obsm['X_pca'] = multivi_sampleid.obsm['MultiVI_latent']

In [ ]:
# need to recompute neighbors because deleted .uns slot to be able to save the adata (see nb)
sc.pp.neighbors(multigrate_modality, use_rep='latent')
sc.pp.neighbors(multigrate_modality_batch_cov, use_rep='latent')

/home/cruiz2/miniconda3/envs/r_python/lib/python3.9/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/cruiz2/miniconda3/envs/r_python/lib/python3.9/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/cruiz2/miniconda3/envs/r_python/lib/python3.9/site-packages/umap/distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/cruiz2/miniconda3/envs/r_python/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/cruiz2/miniconda3/envs/r_python/lib/python3.9/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()

In [ ]:
# Define the list of objects
objects = [multivi_modality, multivi_sampleid,
           glue_modality, glue_modality_batch_cov, 
           multigrate_modality, multigrate_modality_batch_cov]

# Define the list of object names for metrics dataframe
object_names = ['multivi_modality', 'multivi_sampleid',
                'glue_modality', 'glue_modality_batch_cov', 
                'multigrate_modality', 'multigrate_modality_batch_cov']

# Initialize an empty DataFrame
metrics = pd.DataFrame()

# Iterate over the objects and perform metrics calculation
for obj, name in zip(objects, object_names):
    df = scib.metrics.metrics(unintegrated, obj, 'SampleID', 'cell_id',
                              silhouette_=True,
                              graph_conn_=True,
                              # pcr_=True,
                              isolated_labels_asw_=True,
                              hvg_score_=False)
    metrics = pd.concat([metrics, df], axis=1)

Silhouette score...
Isolated labels ASW...
Graph connectivity...
Silhouette score...
Isolated labels ASW...
Graph connectivity...
Silhouette score...
Isolated labels ASW...
Graph connectivity...
Silhouette score...
Isolated labels ASW...
Graph connectivity...
Silhouette score...
Isolated labels ASW...
Graph connectivity...
Silhouette score...
Isolated labels ASW...
Graph connectivity...

In [ ]:
metrics

,0,0,0,0,0,0
NMI_cluster/label,NaN,NaN,NaN,NaN,NaN,NaN
ARI_cluster/label,NaN,NaN,NaN,NaN,NaN,NaN
ASW_label,0.508761,0.532194,0.521688,0.528857,0.515441,0.506008
ASW_label/batch,0.804530,0.790193,0.842088,0.841759,0.759465,0.804571
PCR_batch,NaN,NaN,NaN,NaN,NaN,NaN
cell_cycle_conservation,NaN,NaN,NaN,NaN,NaN,NaN
isolated_label_F1,NaN,NaN,NaN,NaN,NaN,NaN
isolated_label_silhouette,0.527236,0.578781,0.584963,0.592123,0.489735,0.473808
graph_conn,0.802298,0.844478,0.846430,0.837473,0.793344,0.801468
kBET,NaN,NaN,NaN,NaN,NaN,NaN
iLISI,NaN,NaN,NaN,NaN,NaN,NaN
cLISI,NaN,NaN,NaN,NaN,NaN,NaN
hvg_overlap,NaN,NaN,NaN,NaN,NaN,NaN
trajectory,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Transpose the metrics dataframe
metrics = metrics.T
# Set the index and column names
metrics.index = [name + '_embed' for name in object_names]

metrics

,NMI_cluster/label,ARI_cluster/label,ASW_label,ASW_label/batch,PCR_batch,cell_cycle_conservation,isolated_label_F1,isolated_label_silhouette,graph_conn,kBET,iLISI,cLISI,hvg_overlap,trajectory
multivi_modality_embed,NaN,NaN,0.508761,0.804530,NaN,NaN,NaN,0.527236,0.802298,NaN,NaN,NaN,NaN,NaN
multivi_sampleid_embed,NaN,NaN,0.532194,0.790193,NaN,NaN,NaN,0.578781,0.844478,NaN,NaN,NaN,NaN,NaN
glue_modality_embed,NaN,NaN,0.521688,0.842088,NaN,NaN,NaN,0.584963,0.846430,NaN,NaN,NaN,NaN,NaN
glue_modality_batch_cov_embed,NaN,NaN,0.528857,0.841759,NaN,NaN,NaN,0.592123,0.837473,NaN,NaN,NaN,NaN,NaN
multigrate_modality_embed,NaN,NaN,0.515441,0.759465,NaN,NaN,NaN,0.489735,0.793344,NaN,NaN,NaN,NaN,NaN
multigrate_modality_batch_cov_embed,NaN,NaN,0.506008,0.804571,NaN,NaN,NaN,0.473808,0.801468,NaN,NaN,NaN,NaN,NaN

In [ ]:
metrics.to_csv('data/metrics_multi_integration_dmg_atlas.csv', sep=',')