`conda activate r_env`

Idea taken from https://doi.org/10.1038/s41588-022-01243-4 <br>
Code obtained from https://github.com/elo073/5loclung/blob/main/Explained%20Variability/

In [ ]:
suppressPackageStartupMessages({
    library(Seurat)
    library(dplyr)
    library(here)
    library(tibble)
    library(dittoSeq)
    library(stringr)
    library(data.table)
    library(tidyverse)
    library(patchwork) 
    library(RColorBrewer) 
    library(reticulate)
    options(stringsAsFactors = FALSE)
    set.seed(123)
})


source(here("scripts/style.R")) 
source(here("scripts/Barplot.LFLMM.R")) 
source(here("scripts/LFLMM.LMMBF.R")) 
source(here("scripts/functions.R")) 

ggplot2::theme_set(theme_min())

In [ ]:
dmg <- readRDS('/projects/0/einf2548/cruiz/dmg/data/rna_dmg_atlas_scglue_embbeding.rds')
dmg

An object of class Seurat
19248 features across 397794 samples within 1 assay
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 2 dimensional reductions calculated: pca, umap

In [ ]:
dmg <- AddMetaData(dmg, readRDS('../../data/dmg_atlas_final_annotation.rds'))

### All cells

In [ ]:
# Define the percentage of cells you want to subset (e.g., 30%)
subset_percentage <- 0.3

# Get the number of cells to subset
num_cells_subset <- round(ncol(dmg) * subset_percentage)

# Randomly sample cell indices
subset_indices <- sample(1:ncol(dmg), num_cells_subset, replace = FALSE)

# Use the subset function to subset the Seurat object
dmg_subset <- subset(dmg, cells = subset_indices)
dmg_subset

An object of class Seurat
19248 features across 119338 samples within 1 assay
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 2 dimensional reductions calculated: pca, umap

In [ ]:
norm_counts <- as.data.frame(GetAssayData(dmg_subset, slot='data'))

In [ ]:
dim(norm_counts)
percent <- dim(norm_counts)[2]*0.95
norm_counts <- norm_counts[rowSums(norm_counts == 0) <= percent, ]
dim(norm_counts)

[1]  19248 119338

[1]  10509 119338

In [ ]:
mdata <- dmg_subset@meta.data %>% select(c('nCount_RNA', 'nFeature_RNA',
                                           'SampleID', 'percent_mito', 'percent_ribo', 
                                           'Batch_for_correction','Study', 'Location',
                                           'Tumor_subtype', 'lvl_1'))

In [ ]:
# Logaritmize Total counts and Number of Genes
mdata$nCount_RNA=log(mdata$nCount_RNA)
mdata$nFeature_RNA=log(mdata$nFeature_RNA)

In [ ]:
# fitting lmm
res = LFLMM(norm_counts, mdata)

           Intercept           nCount_RNA         nFeature_RNA
                   1                    1                    1
            SampleID         percent_mito         percent_ribo
                  83                    1                    1
Batch_for_correction                Study             Location
                   4                    2                    6
       Tumor_subtype                lvl_1
                   4                    5
[1] "matrix prep 2"
[1] "Y"
[1]  10509 119338
      BT042_PD_CCTGCATAGGTCACAG-1 BT042_PD_ACAAGCTGTGGCTAGA-1
A1BG                            0                           0
A2M                             0                           0
AAAS                            0                           0
AACS                            0                           0
AADAT                           0                           0
      BT042_PD_TACTTACCAAGTACCT-1 BT042_PD_TGCGACGCAGCTGTGC-1
A1BG                            0                    0.000000
A2M                             0                    1.100591
AAAS                            0                    0.000000
AACS                            0                    0.000000
AADAT                           0                    0.000000
      BT042_PD_TAAGTCGGTCGCAGTC-1
A1BG                            0
A2M                             0
AAAS                            0
AACS                            0
AADAT                           0
[1] "Z"
[1] 119338    109
     Z nCount_RNA nFeature_RNA BT042_PD BT042_pons_1
[1,] 1  0.3588990    0.1128413        1            0
[2,] 1  0.3518301    0.1362512        1            0
[3,] 1 -0.1283295   -0.3740147        1            0
[4,] 1 -0.1652681   -0.1029154        1            0
[5,] 1 -0.1487601   -0.3148157        1            0
[1] "matrix prep end"
[ 1 ][1] "psi"
 [1] 3.89578454 0.42766381 0.01543181 2.21551684 0.13870679 1.39194853
 [7] 0.17299565 0.07290632 0.02561118 0.05239856 3.69988262
[ 2 ][1] "psi"
 [1] 1.94760668 0.21439082 1.27326802 1.11852121 0.07701345 0.70526567
 [7] 0.09503813 0.04879152 0.05533949 0.03815109 1.86073157
[ 3 ][1] "psi"
 [1] 0.99483025 0.21732316 0.65107220 0.58077054 0.05375736 0.37275252
 [7] 0.06376056 0.04206408 0.04658620 0.03542013 0.95456864
[ 4 ][1] "psi"
 [1] 0.54217652 0.21707012 0.35498117 0.33238007 0.04873453 0.22491093
 [7] 0.05723869 0.04094394 0.04580539 0.03550249 0.52581087
[ 5 ][1] "psi"
 [1] 0.35361844 0.21650349 0.23174885 0.23968455 0.04849165 0.17652693
 [7] 0.05956355 0.03995651 0.04575801 0.03588166 0.35145245
[ 6 ][1] "psi"
 [1] 0.30306384 0.21558889 0.19887833 0.22167096 0.04851028 0.17000230
 [7] 0.06200599 0.03936553 0.04565971 0.03618769 0.30827170
[ 7 ][1] "psi"
 [1] 0.29874531 0.21509444 0.19608874 0.22089198 0.04851096 0.16989591
 [7] 0.06276324 0.03919331 0.04564535 0.03630048 0.30523677
[ 8 ][1] "psi"
 [1] 0.29871144 0.21504546 0.19605942 0.22088398 0.04851001 0.16989492
 [7] 0.06286018 0.03915552 0.04564459 0.03632028 0.30522074
Converged

In [ ]:
Barplot(res, "figures/explained_variance_all.pdf", "All cells")

                     varexp    varse
lvl_1                7.3548646 7.4478374
SampleID             3.8517748 3.8656508
nCount_RNA           3.6522403 3.7482471
nFeature_RNA         3.0353326 3.1157683
percent_ribo         2.2785932 2.3389667
Batch_for_correction 0.3109651 0.3250645
percent_mito         0.1857722 0.1908358
Location             0.1644728 0.1722348
Study                0.1212621 0.1364270
Tumor_subtype        0.1040221 0.1099718

### Nuclei

In [ ]:
dmg_subset$Material <- recode(dmg_subset$Batch_for_correction,
                          '10Xv1_nuclei_multiome' = 'nuclei',
                           '10Xv3_cell_rna'='cell',
                           '10Xv3_nuclei_rna'='nuclei',
                           '10Xv3.1_nuclei_rna'='nuclei')

In [ ]:
# Use the subset function to subset the Seurat object
nuclei <- subset(dmg_subset, Material=='nuclei')
nuclei

An object of class Seurat
19248 features across 102100 samples within 1 assay
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 2 dimensional reductions calculated: pca, umap

In [ ]:
norm_counts <- as.data.frame(GetAssayData(nuclei, slot='data'))

In [ ]:
dim(norm_counts)
percent <- dim(norm_counts)[2]*0.95
norm_counts <- norm_counts[rowSums(norm_counts == 0) <= percent, ]
dim(norm_counts)

[1]  19248 102100

[1]  10427 102100

In [ ]:
mdata <- nuclei@meta.data %>% select(c('nCount_RNA', 'nFeature_RNA',
                                           'SampleID', 'percent_mito', 'percent_ribo', 
                                           'Batch_for_correction','Study', 'Location',
                                           'Tumor_subtype', 'lvl_1'))
mdata

In [ ]:
# Logaritmize Total counts and Number of Genes
mdata$nCount_RNA=log(mdata$nCount_RNA)
mdata$nFeature_RNA=log(mdata$nFeature_RNA)
mdata

In [ ]:
# fitting lmm
res = LFLMM(norm_counts, mdata)

           Intercept           nCount_RNA         nFeature_RNA
                   1                    1                    1
            SampleID         percent_mito         percent_ribo
                  78                    1                    1
Batch_for_correction                Study             Location
                   3                    2                    6
       Tumor_subtype                lvl_1
                   4                    5
[1] "matrix prep 2"
[1] "Y"
[1]  10427 102100
      BT042_PD_CCTGCATAGGTCACAG-1 BT042_PD_ACAAGCTGTGGCTAGA-1
A1BG                            0                           0
A2M                             0                           0
AAAS                            0                           0
AACS                            0                           0
AADAT                           0                           0
      BT042_PD_TACTTACCAAGTACCT-1 BT042_PD_TGCGACGCAGCTGTGC-1
A1BG                            0                    0.000000
A2M                             0                    1.100591
AAAS                            0                    0.000000
AACS                            0                    0.000000
AADAT                           0                    0.000000
      BT042_PD_TAAGTCGGTCGCAGTC-1
A1BG                            0
A2M                             0
AAAS                            0
AACS                            0
AADAT                           0
[1] "Z"
[1] 102100    103
     Z nCount_RNA nFeature_RNA BT042_PD BT042_pons_1
[1,] 1  0.3347079   0.06667014        1            0
[2,] 1  0.3274466   0.09131891        1            0
[3,] 1 -0.1657781  -0.44594990        1            0
[4,] 1 -0.2037218  -0.16050424        1            0
[5,] 1 -0.1867647  -0.38361818        1            0
[1] "matrix prep end"
[ 1 ][1] "psi"
 [1] 4.106622965 0.448794562 0.004345754 2.116534298 0.093377105 0.641459640
 [7] 0.178253097 0.032031102 0.070047340 0.069437412 3.640869023
[ 2 ][1] "psi"
 [1] 2.05148827 0.19791562 4.00157013 1.06941258 0.05587243 0.32915938
 [7] 0.09533735 0.03780004 0.05469041 0.04480496 1.83225343
[ 3 ][1] "psi"
 [1] 1.04580888 0.21007118 1.99426771 0.55658466 0.04473059 0.18117370
 [7] 0.06162546 0.03235658 0.05159207 0.03747961 0.94135570
[ 4 ][1] "psi"
 [1] 0.56649626 0.20956645 1.00391103 0.32095217 0.04332787 0.12094238
 [7] 0.05301777 0.03163557 0.05140155 0.03688329 0.52119907
[ 5 ][1] "psi"
 [1] 0.36469174 0.20922660 0.51864746 0.23465543 0.04329063 0.10609346
 [7] 0.05354621 0.03153099 0.05133697 0.03720187 0.35232035
[ 6 ][1] "psi"
 [1] 0.30933118 0.20870882 0.29217225 0.21876340 0.04327155 0.10519208
 [7] 0.05421086 0.03222753 0.05150280 0.03752168 0.31190703
[ 7 ][1] "psi"
 [1] 0.30450958 0.20810044 0.20441428 0.21816019 0.04325946 0.10522796
 [7] 0.05416910 0.03273109 0.05161601 0.03763182 0.30927476
[ 8 ][1] "psi"
 [1] 0.30446540 0.20732868 0.18556980 0.21815212 0.04325003 0.10522618
 [7] 0.05413424 0.03279934 0.05163310 0.03764835 0.30926335
[ 9 ][1] "psi"
 [1] 0.30446237 0.20700755 0.18460097 0.21814975 0.04324616 0.10522473
 [7] 0.05412707 0.03280975 0.05163477 0.03765096 0.30926373
Converged

In [ ]:
Barplot(res, "figures/explained_variance_nuclei.pdf", "Nuclei")

                     varexp     varse
lvl_1                7.70272382 7.7999562
SampleID             3.83271280 3.8467042
nCount_RNA           3.46183361 3.5534770
nFeature_RNA         2.77333305 2.8474250
percent_ribo         0.89173339 0.9158086
Batch_for_correction 0.23601060 0.2511576
Location             0.21470585 0.2239902
percent_mito         0.15064689 0.1547774
Tumor_subtype        0.11415087 0.1204881
Study                0.08663981 0.1020212

### Cell

In [ ]:
# Use the subset function to subset the Seurat object
cell <- subset(dmg_subset, Material=='cell')
cell

An object of class Seurat
19248 features across 17238 samples within 1 assay
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 2 dimensional reductions calculated: pca, umap

In [ ]:
norm_counts <- as.data.frame(GetAssayData(cell, slot='data'))

In [ ]:
dim(norm_counts)
percent <- dim(norm_counts)[2]*0.95
norm_counts <- norm_counts[rowSums(norm_counts == 0) <= percent, ]
dim(norm_counts)

[1] 19248 17238

[1] 10142 17238

In [ ]:
mdata <- cell@meta.data %>% select(c('nCount_RNA', 'nFeature_RNA',
                                           'SampleID', 'percent_mito', 'percent_ribo', 
                                            'Location',
                                           'Tumor_subtype', 'lvl_1'))
mdata

In [ ]:
# Logaritmize Total counts and Number of Genes
mdata$nCount_RNA=log(mdata$nCount_RNA)
mdata$nFeature_RNA=log(mdata$nFeature_RNA)
mdata

In [ ]:
# fitting lmm
res = LFLMM(norm_counts, mdata)

    Intercept    nCount_RNA  nFeature_RNA      SampleID  percent_mito
            1             1             1             5             1
 percent_ribo      Location Tumor_subtype         lvl_1
            1             3             2             5
[1] "matrix prep 2"
[1] "Y"
[1] 10142 17238
      rna_P-6117_S-8370_GCTGCAGCACCATCCT-1 rna_P-6117_S-8370_GCAGCCACAGTGACAG-1
A1BG                             0.1316070                            0.1512442
A2M                              0.0000000                            0.0000000
AAAS                             0.1316070                            0.1512442
AACS                             0.2478906                            0.1512442
AAGAB                            0.2478906                            0.1512442
      rna_P-6117_S-8370_GACCAATTCCCTAATT-1 rna_P-6117_S-8370_GTGCGGTTCTCTAGGA-1
A1BG                             0.0000000                            0.4777703
A2M                              0.7656643                            0.0000000
AAAS                             0.2527844                            0.1424702
AACS                             0.0000000                            0.0000000
AAGAB                            0.1343585                            0.2671509
      rna_P-6117_S-8370_GGACAGATCTGGTTCC-1
A1BG                             0.1384526
A2M                              0.0000000
AAAS                             0.0000000
AACS                             0.1384526
AAGAB                            0.0000000
[1] "Z"
[1] 17238    20
     Z nCount_RNA nFeature_RNA P-6117_S-8370_RNA_only P-6240_S-8628_RNA_only
[1,] 1   2.299059     1.801143                      1                      0
[2,] 1   2.262603     1.720090                      1                      0
[3,] 1   2.203688     1.812905                      1                      0
[4,] 1   2.184224     1.820624                      1                      0
[5,] 1   2.201799     1.816535                      1                      0
[1] "matrix prep end"
[ 1 ][1] "psi"
[1]  1.5003150 -0.0122035  0.1630312  1.8477841  0.1441267  1.6235586 -0.2616423
[8]  0.7326204  2.7269007
[ 2 ][1] "psi"
[1]  0.78265159 -2.54188979 -0.08344284  0.93772336  0.07884170  0.82508507
[7] -0.11693978  0.36782596  1.38134106
[ 3 ][1] "psi"
[1]  0.45693179 -1.27232889 -0.57735541  0.49592078  0.05353297  0.43914819
[7] -0.03208827  0.18577360  0.72666342
[ 4 ][1] "psi"
[1]  0.34156815 -0.66653533 -0.36533470  0.29922148  0.04996415  0.26965567
[7]  0.07185823  0.09432592  0.43200268
[ 5 ][1] "psi"
[1]  0.323682399 -0.390172900 -0.302325224  0.235750010  0.049581427
[6]  0.216524316 -0.005323972  0.043048413  0.331673661
[ 6 ][1] "psi"
[1]  0.326936049 -0.289780161 -0.291090583  0.227511401  0.049361803
[6]  0.210038224  0.532838493 -0.004155035  0.316654968
[ 7 ][1] "psi"
[1]  0.30995388 -0.27171677 -0.28541998  0.23189651  0.04923288  0.21007529
[7]  0.24894524 -1.62179097  0.31643293
[ 8 ][1] "psi"
[1]  0.30306408 -0.27050363 -0.28357425  0.23221020  0.04921945  0.21013291
[7]  0.11286979 -0.80802916  0.31647333
[ 9 ][1] "psi"
[1]  0.30288046 -0.27021330 -0.28335913  0.23211868  0.04920499  0.21009855
[7]  0.03087240 -0.40000525  0.31643948
[ 10 ][1] "psi"
[1]  0.30545412 -0.27011451 -0.28326122  0.23155695  0.04918303  0.21004411
[7] -0.07778069 -0.19425360  0.31639304
[ 11 ][1] "psi"
[1]  0.3136639347 -0.2701641863 -0.2832617435  0.2300533926  0.0491570143
[6]  0.2100071358 -0.0003929342 -0.0903317229  0.3163696082
[ 12 ][1] "psi"
[1]  0.32304680 -0.27013055 -0.28319795  0.22000929  0.04914855  0.20997971
[7]  0.16312901 -0.02164694  0.31634780
[ 13 ][1] "psi"
[1]  0.322527179 -0.270277216 -0.283325673  0.229851129  0.049153959
[6]  0.210026205  0.057908853  0.005379696  0.316370739
[ 14 ][1] "psi"
[1]  0.32732691 -0.27017892 -0.28322282  0.22764507  0.04914491  0.20997879
[7] -0.02293918 -0.18405683  0.31635050
[ 15 ][1] "psi"
[1]  0.31478948 -0.27010935 -0.28322595  0.23003696  0.04916660  0.21001329
[7]  0.11407870 -0.08268973  0.31636500
[ 16 ][1] "psi"
[1]  0.32169826 -0.27021859 -0.28327326  0.22894807  0.04914592  0.20999725
[7]  0.02790038 -0.03274141  0.31636517
[ 17 ][1] "psi"
[1]  0.32730973 -0.27014909 -0.28319577  0.22750705  0.04914636  0.20997616
[7] -0.08991366  0.01801889  0.31634573
[ 18 ][1] "psi"
[1]  0.326053895 -0.270197534 -0.283241907  0.228291746  0.049147687
[6]  0.209992981 -0.009503551 -0.043368772  0.316357950
[ 19 ][1] "psi"
[1]  0.326979178 -0.270137213 -0.283188217  0.227652633  0.049149257
[6]  0.209979191  0.297412859  0.006718235  0.316346122
[ 20 ][1] "psi"
[1]  0.31727608 -0.27033044 -0.28339806  0.23098784  0.04915509  0.21004650
[7]  0.13011906  0.25592509  0.31640237
[ 21 ][1] "psi"
[1]  0.31035900 -0.27022657 -0.28333565  0.23094932  0.04916557  0.21003374
[7]  0.04113610  0.12236485  0.31639090
[ 22 ][1] "psi"
[1]  0.31977213 -0.27014835 -0.28322860  0.22878148  0.04915071  0.20998725
[7] -0.05040871  0.05139213  0.31635449
[ 23 ][1] "psi"
[1]  0.325765506 -0.270158337 -0.283207360  0.227869404  0.049146623
[6]  0.209981406  0.033645360  0.004676315  0.316349481
[ 24 ][1] "psi"
[1]  0.32807533 -0.27014747 -0.28318937  0.22751274  0.04914743  0.20997864
[7] -0.06971434 -0.24612467  0.31634606
[ 25 ][1] "psi"
[1]  0.311089000 -0.270138458 -0.283264174  0.230839070  0.049171956
[6]  0.210032433  0.007252788 -0.115541895  0.316379897
[ 26 ][1] "psi"
[1]  0.32059602 -0.27012727 -0.28320426  0.22856869  0.04915048  0.20998362
[7] -0.39266927 -0.04708380  0.31635101
[ 27 ][1] "psi"
[1]  0.31398785 -0.27034886 -0.28342205  0.23151039  0.04916024  0.21006132
[7] -0.17915991 -0.09284740  0.31641561
[ 28 ][1] "psi"
[1]  0.31904330 -0.27029113 -0.28335587  0.22984890  0.04914694  0.21001226
[7] -0.06777480 -0.04595218  0.31638095
[ 29 ][1] "psi"
[1]  0.325603521 -0.270187465 -0.283237348  0.227961998  0.049145249
[6]  0.209982237  0.011103936 -0.001994652  0.316352864
[ 30 ][1] "psi"
[1]  0.32828695 -0.27014052 -0.28318260  0.22733068  0.04914761  0.20997617
[7] -0.25443682  0.56439845  0.31634400
[ 31 ][1] "psi"
[1]  0.30519293 -0.27029226 -0.28340182  0.23207850  0.04918986  0.21010022
[7] -0.11497412  0.27854725  0.31643908
[ 32 ][1] "psi"
[1]  0.30916432 -0.27021034 -0.28332315  0.23100617  0.04916603  0.21003048
[7] -0.03104021  0.13381010  0.31638868
[ 33 ][1] "psi"
[1]  0.31876812 -0.27013779 -0.28322415  0.22893469  0.04915208  0.20998837
[7]  0.07779029  0.05751640  0.31635459
[ 34 ][1] "psi"
[1]  0.3245844896 -0.2701835826 -0.2832333890  0.2282440548  0.0491461209
[6]  0.2099875494 -0.0009439509  0.0121667764  0.3163552495
[ 35 ][1] "psi"
[1]  0.3282949 -0.2701387 -0.2831817  0.2228481  0.0491472  0.2099754  1.3960771
[8] -0.1334068  0.3163438
[ 36 ][1] "psi"
[1]  0.30531520 -0.27038229 -0.28347243  0.23240211  0.04920545  0.21014955
[7]  0.68881707 -0.14628279  0.31647357
[ 37 ][1] "psi"
[1]  0.30799716 -0.27039061 -0.28347509  0.23205851  0.04917851  0.21009332
[7]  0.33058881 -0.12066523  0.31644667
[ 38 ][1] "psi"
[1]  0.31393271 -0.27035849 -0.28343375  0.23122035  0.04915522  0.21004420
[7]  0.14808741 -0.07831591  0.31640769
[ 39 ][1] "psi"
[1]  0.32085464 -0.27026976 -0.28332985  0.22933238  0.04914526  0.21000286
[7]  0.04952434 -0.03479545  0.31637288
[ 40 ][1] "psi"
[1]  0.32673903 -0.27016949 -0.28321649  0.22768362  0.04914575  0.20997871
[7] -0.03513338  0.01283684  0.31634891
[ 41 ][1] "psi"
[1]  0.32795155 -0.27014886 -0.28319165  0.22756775  0.04914808  0.20997983
[7]  0.06543761 -0.08501214  0.31634658
[ 42 ][1] "psi"
[1]  0.32299716 -0.27016186 -0.28322768  0.22866983  0.04915315  0.20999619
[7] -0.01329605 -0.02798477  0.31635761
[ 43 ][1] "psi"
[1]  0.32771638 -0.27013958 -0.28318354  0.22743206  0.04914684  0.20997554
[7]  0.20950021  0.02749035  0.31634454
[ 44 ][1] "psi"
[1]  0.32052095 -0.27029552 -0.28335410  0.23014898  0.04915058  0.21002743
[7]  0.08395492  0.02415662  0.31638673
[ 45 ][1] "psi"
[1]  0.325981743 -0.270205934 -0.283251757  0.228034105  0.049144181
[6]  0.209984435  0.004415677 -0.023146192  0.316356024
[ 46 ][1] "psi"
[1]  0.32800724 -0.27013969 -0.28318481  0.22747181  0.04914826  0.20997698
[7] -0.64836380  0.04054285  0.31634450
[ 47 ][1] "psi"
[1]  0.3098102 -0.2703665 -0.2834516  0.2320739  0.0491784  0.2100989 -0.3096221
[8]  0.1836759  0.3164430
[ 48 ][1] "psi"
[1]  0.31241355 -0.27034763 -0.28342754  0.23129336  0.04915857  0.21004759
[7] -0.13874280  0.09900517  0.31640961
[ 49 ][1] "psi"
[1]  0.31987178 -0.27025832 -0.28332351  0.22939445  0.04914655  0.21000279
[7] -0.04414506  0.04444669  0.31637209
[ 50 ][1] "psi"
[1]  0.326341352 -0.270163394 -0.283212766  0.227709702  0.049146078
[6]  0.209978381  0.044629748 -0.001960206  0.316348361
[ 51 ][1] "psi"
[1]  0.32772547 -0.27015578 -0.28319760  0.22756745  0.04914761  0.20998090
[7] -0.04416058  0.54398390  0.31634774
[ 52 ][1] "psi"
[1]  0.30468709 -0.27009817 -0.28326224  0.23197508  0.04919916  0.21007775
[7]  0.04306564  0.26675395  0.31641111
[ 53 ][1] "psi"
[1]  0.30947971 -0.27012219 -0.28324526  0.23076426  0.04916769  0.21001885
[7] -0.04569146  0.12677965  0.31637546
[ 54 ][1] "psi"
[1]  0.31932461 -0.27014228 -0.28322174  0.22887932  0.04915066  0.20998885
[7]  0.04129207  0.05394929  0.31635533
[ 55 ][1] "psi"
[1]  0.325786975 -0.270149931 -0.283200240  0.227807751  0.049146746
[6]  0.209979893 -0.050393193  0.006422144  0.316348137
[ 56 ][1] "psi"
[1]  0.32764504 -0.27015932 -0.28320115  0.22767776  0.04914723  0.20998167
[7]  0.03374116 -0.17012344  0.31634868
[ 57 ][1] "psi"
[1]  0.31586078 -0.27011643 -0.28322607  0.22985736  0.04916452  0.21001093
[7] -0.06887993 -0.07536704  0.31636409
[ 58 ][1] "psi"
[1]  0.323524782 -0.270172313 -0.283226978  0.228302241  0.049146398
[6]  0.209985893  0.009715278 -0.024413876  0.316354600
[ 59 ][1] "psi"
[1]  0.32789996 -0.27013838 -0.28318260  0.22741942  0.04914710  0.20997570
[7] -0.29071175  0.03582175  0.31634407
[ 60 ][1] "psi"
[1]  0.31739458 -0.27032786 -0.28339616  0.23096929  0.04915538  0.21004640
[7] -0.12687962  0.05951037  0.31640179
[ 61 ][1] "psi"
[1]  0.32268217 -0.27024934 -0.28330424  0.22890469  0.04914472  0.20999687
[7] -0.03615482  0.02068891  0.31636763
[ 62 ][1] "psi"
[1]  0.32764253 -0.27015813 -0.28320231  0.22749686  0.04914617  0.20997669
[7]  0.06268896 -0.04305039  0.31634647
[ 63 ][1] "psi"
[1]  0.326076776 -0.270167518 -0.283216940  0.228090823  0.049149429
[6]  0.209988463 -0.016809333  0.004766513  0.316353019
[ 64 ][1] "psi"
[1]  0.32833374 -0.27014039 -0.28318248  0.22741213  0.04914762  0.20997670
[7]  0.16272597 -0.24740417  0.31634465
[ 65 ][1] "psi"
[1]  0.31126475 -0.27024128 -0.28334283  0.23112610  0.04916776  0.21004736
[7]  0.06129637 -0.11849144  0.31639678
[ 66 ][1] "psi"
[1]  0.31992159 -0.27016768 -0.28324431  0.22884647  0.04914979  0.20998951
[7] -0.01803639 -0.04981029  0.31635749
[ 67 ][1] "psi"
[1]  0.326421220 -0.270139597 -0.283189453  0.227620615  0.049147061
[6]  0.209976826  0.150629936 -0.001708935  0.316345375
[ 68 ][1] "psi"
[1]  0.32326340 -0.27025630 -0.28330533  0.22921656  0.04914755  0.21000979
[7]  0.05036237  0.17863885  0.31637278
[ 69 ][1] "psi"
[1]  0.31503476 -0.27013956 -0.28324914  0.22993975  0.04916280  0.21001038
[7] -0.03283603  0.08051120  0.31636703
[ 70 ][1] "psi"
[1]  0.32376067 -0.27014285 -0.28320246  0.22805962  0.04914752  0.20998027
[7]  0.07209450  0.02615263  0.31634901
[ 71 ][1] "psi"
[1]  0.326441866 -0.270179132 -0.283222850  0.227988036  0.049146525
[6]  0.209986229 -0.006628802 -0.025223316  0.316353154
[ 72 ][1] "psi"
[1]  0.32793114 -0.27013702 -0.28318255  0.22749393  0.04914846  0.20997755
[7]  0.42989204  0.03554538  0.31634478
[ 73 ][1] "psi"
[1]  0.31359198 -0.27035295 -0.28343117  0.23168084  0.04916474  0.21007110
[7]  0.19828599  0.12249949  0.31642128
[ 74 ][1] "psi"
[1]  0.31696622 -0.27030170 -0.28337265  0.23026619  0.04914987  0.21002033
[7]  0.07895271  0.06168899  0.31638721
[ 75 ][1] "psi"
[1]  0.3242568211 -0.2701981910 -0.2832526643  0.2282437798  0.0491453848
[6]  0.2099854865  0.0001528866  0.0160868032  0.3163560273
[ 76 ][1] "psi"
[1]  0.328204232 -0.270140140 -0.283183497  0.219017498  0.049147290
[6]  0.209975418 -0.009737137 -0.124698545  0.316343723
[ 77 ][1] "psi"
[1]  0.31967217 -0.27010656 -0.28320004  0.22956381  0.04916833  0.21001261
[7]  0.29000067 -0.04890514  0.31634884
[ 78 ][1] "psi"
[1]  0.31687321 -0.27032724 -0.28339112  0.23088715  0.04915234  0.21004003
[7]  0.12640052 -0.05761487  0.31640062
[ 79 ][1] "psi"
[1]  0.32279694 -0.27024852 -0.28330332  0.22887605  0.04914441  0.20999635
[7]  0.03581260 -0.01956090  0.31636716
[ 80 ][1] "psi"
[1]  0.32768550 -0.27015786 -0.28320184  0.22749063  0.04914619  0.20997665
[7] -0.06360381  0.04678332  0.31634641
[ 81 ][1] "psi"
[1]  0.3258380362 -0.2701678390 -0.2832184415  0.2281412489  0.0491496893
[6]  0.2099891865  0.0157066309 -0.0008914657  0.3163534833
[ 82 ][1] "psi"
[1]  0.32700327 -0.27014037 -0.28318225  0.22669781  0.04914752  0.20997640
[7] -0.18783606  0.43260907  0.31634426
[ 83 ][1] "psi"
[1]  0.30626460 -0.27025384 -0.28336986  0.23188116  0.04918354  0.21008037
[7] -0.07753077  0.21174673  0.31642045
[ 84 ][1] "psi"
[1]  0.3125097266 -0.2701719660 -0.2832790625  0.2302724073  0.0491598274
[6]  0.2100109389 -0.0003158626  0.0992258458  0.3163725270
[ 85 ][1] "psi"
[1]  0.32219230 -0.27013051 -0.28320167  0.22005561  0.04914923  0.20998095
[7]  0.08485666  0.02793019  0.31634871
[ 86 ][1] "psi"
[1]  0.326005011 -0.270196050 -0.283237020  0.228583610  0.049153307
[6]  0.210001583  0.005219934 -0.024205752  0.316349655
Converged

In [ ]:
Barplot(res, "figures/explained_variance_cells.pdf", "Cells")

              varexp       varse
lvl_1         7.4028200752 7.51351888
nFeature_RNA  5.9340976808 6.09616509
nCount_RNA    5.3998792217 5.54837044
SampleID      3.8439573558 3.91872568
percent_ribo  3.2615103945 3.34921455
percent_mito  0.1786556410 0.18381869
Location      0.0091202678 0.07468197
Tumor_subtype 0.0002942983 0.07699646